### ISSUE TITLE
Cannot start migrations

### ISSUE THREAD

**Issue by anime-shed** [JetBrains/rider-efcore#197]
#### Describe the bug

I am unable to execute the dotnet-ef using the GUI available in Rider; instead, it shows an error that `dotnet-ef` is not found, and when I try to fix it, it presents me with `Tool 'dotnet-ef' is already installed.` I also verified it from a terminal and also was able to run migrations via cli.

**To Reproduce**

Steps to reproduce the behaviour:

![image](https://github.com/JetBrains/rider-efcore/assets/67512697/ecd8f3ed-51ff-4415-96e4-b7b56f1ee307)
#### Expected behaviour

A window should open with other options to proceed

#### Screenshots

![image](https://github.com/JetBrains/rider-efcore/assets/67512697/4fdc7e8a-84e7-425f-a373-db4a0270425b)
![image](https://github.com/JetBrains/rider-efcore/assets/67512697/67fa4284-69d2-4a14-a277-9a930ed17d79)
![image](https://github.com/JetBrains/rider-efcore/assets/67512697/cf3ab4e2-453b-4b50-ac8c-180778f16def)

### Environment (please complete the following information):

- OS: Windows
- .NET SDK info (installed ones and versions used within Rider): 8.0, 6.0
- Plugin version: 232.1.0
- Rider version: 2023.2.1

**Comment by seclerp** [comment]
Hi @anime-shed, on which level dotnet ef tools are installed? As a local tool on the solution level or as a global tool?

**Comment by seclerp** [comment]
And does restarting Rider fix the issue?

**Comment by roberto-sotar** [comment]
same issue with EF core tools, with rider 2023.2.3, .NET6, macos sonoma, plugin EntityFrameWork Core UI 232.1.0, the plugin try to install v8.0.0 from EF Core and isn't compatible with .NET6
![Screenshot 2023-11-17 at 11 50 29](https://github.com/JetBrains/rider-efcore/assets/146682871/bada9322-3dfd-4101-aa29-0fefeebf8abd)
 Any news about this bug ?

**Comment by seclerp** [comment]
@roberto-sotar Currently there is no way of installing a _specific_ `dotnet ef` tools version. The plugin always installs the latest stable version globally it it isn't already installed (quite oftenly, they are backward compatible). Because of that we can't rely on specific EF Core version of your solution (global tools are installed in per-machine basis).

So you have 2 options here:
1. Install EF Core Tools globally with a specific version: `dotnet tool install --global dotnet-ef --version 6.0.25`
1. Install EF Core Tools locally **inside solution folder** `dotnet tool install dotnet-ef --version 6.0.25`
    > In case you don't have a tool manifest file run `dotnet new tool-manifest` before installing tools locally
    
After installation, the EF Core UI plugin will acknowledge installed tools and you'll be able to perform migrations.

Please note, sometimes Rider doesn't see tools installed right after installation. It's a known issue and is already addressed in the upcoming 2023.3 release.

**Comment by my-dev-92** [comment]
@seclerp hello!
I have a question related to local dotnet tools. I have several projects with EF Core, but with different versions. Each project has specific dotnet tools. How can I switch to local dotnet tools instead of the global version?

**Comment by seclerp** [comment]
Hi @my-dev-92, currently you can use one of 2 options:
- Globally installed tools (e.g. `dotnet tool install --global`, Rider installs tools this way when you do it using the "Install" action)
- Locally installed **in Solution** (e.g. `dotnet tool install` on Solution level with Solution level tool manifest)

So Project-level tools are not supported yet. Please open a ticket on [YouTrack](https://youtrack.jetbrains.com/newIssue) but no ETA for now.

**Comment by my-dev-92** [comment]
> Hi @my-dev-92, currently you can use one of 2 options:
> 
> * Globally installed tools (e.g. `dotnet tool install --global`, Rider installs tools this way when you do it using the "Install" action)
> * Locally installed **in Solution** (e.g. `dotnet tool install` on Solution level with Solution level tool manifest)
> 
> So Project-level tools are not supported yet. Please open a ticket on [YouTrack](https://youtrack.jetbrains.com/newIssue) but no ETA for now.

Sorry, I meant solutions instead of projects. E.g. Solution1 has a project with EF Core 6.x.x version and Solution2 has a project with EF Core 7.x.x version. And each of the solutions has a tool manifest file `dotnet-tools.json`.
I thought that locally installed in Solution was used in EF Core UI. But I see the following:
![image](https://github.com/JetBrains/rider-efcore/assets/31287817/a5195033-eb82-4567-9630-c068c0cabfc7)

**Comment by seclerp** [comment]
@my-dev-92 could you please provide more details about your Solution's folder structure?

**Comment by seclerp** [comment]
I'm closing this due to lack of information, please reopen if needed
